/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApartamentaiRouteImport } from './routes/apartamentai'
import { Route as ApieRouteImport } from './routes/apie'
import { Route as BanketineSaleRouteImport } from './routes/banketine-sale'
import { Route as DovanuKuponaiRouteImport } from './routes/dovanu-kuponai'
import { Route as EnRouteRouteImport } from './routes/en/route'
import { Route as HomeV2RouteImport } from './routes/home-v2'
import { Route as KontaktaiRouteImport } from './routes/kontaktai'
import { Route as LaisviKambariaiRouteImport } from './routes/laisvi-kambariai'
import { Route as NamelisRouteImport } from './routes/namelis'
import { Route as PrivatumoPolitikaRouteImport } from './routes/privatumo-politika'
import { Route as RestobarasRouteImport } from './routes/restobaras'
import { Route as SaunaRouteImport } from './routes/sauna'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TaisyklesRouteImport } from './routes/taisykles'
import { Route as ApartamentaiIndexRouteImport } from './routes/apartamentai.index'
import { Route as ApartamentaiPropertyIdRouteImport } from './routes/apartamentai.$propertyId'
import { Route as ApartamentaiStandartiniaiRouteImport } from './routes/apartamentai.standartiniai'
import { Route as ApartamentaiSuTerasaRouteImport } from './routes/apartamentai.su-terasa'
import { Route as ApieIndexRouteImport } from './routes/apie.index'
import { Route as ApieTaisyklesRouteImport } from './routes/apie.taisykles'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as EnApartamentaiRouteImport } from './routes/en/apartamentai'
import { Route as EnApieRouteImport } from './routes/en/apie'
import { Route as EnBanketineSaleRouteImport } from './routes/en/banketine-sale'
import { Route as EnDovanuKuponaiRouteImport } from './routes/en/dovanu-kuponai'
import { Route as EnHomeV2RouteImport } from './routes/en/home-v2'
import { Route as EnKontaktaiRouteImport } from './routes/en/kontaktai'
import { Route as EnLaisviKambariaiRouteImport } from './routes/en/laisvi-kambariai'
import { Route as EnNamelisRouteImport } from './routes/en/namelis'
import { Route as EnPrivatumoPolitikaRouteImport } from './routes/en/privatumo-politika'
import { Route as EnRestobarasRouteImport } from './routes/en/restobaras'
import { Route as EnSaunaRouteImport } from './routes/en/sauna'
import { Route as EnTaisyklesRouteImport } from './routes/en/taisykles'
import { Route as RezervacijaPatvirtintaRouteImport } from './routes/rezervacija.patvirtinta'
import { Route as ApartamentaiTipasCategorySlugRouteImport } from './routes/apartamentai.tipas.$categorySlug'
import { Route as EnApartamentaiIndexRouteImport } from './routes/en/apartamentai.index'
import { Route as EnApartamentaiPropertyIdRouteImport } from './routes/en/apartamentai.$propertyId'
import { Route as EnApartamentaiStandartiniaiRouteImport } from './routes/en/apartamentai.standartiniai'
import { Route as EnApartamentaiSuTerasaRouteImport } from './routes/en/apartamentai.su-terasa'
import { Route as EnApieIndexRouteImport } from './routes/en/apie.index'
import { Route as EnApieTaisyklesRouteImport } from './routes/en/apie.taisykles'
import { Route as EnRezervacijaPatvirtintaRouteImport } from './routes/en/rezervacija.patvirtinta'
import { Route as EnApartamentaiTipasCategorySlugRouteImport } from './routes/en/apartamentai.tipas.$categorySlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentaiRoute = ApartamentaiRouteImport.update({
  id: '/apartamentai',
  path: '/apartamentai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApieRoute = ApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => rootRouteImport,
} as any)
const BanketineSaleRoute = BanketineSaleRouteImport.update({
  id: '/banketine-sale',
  path: '/banketine-sale',
  getParentRoute: () => rootRouteImport,
} as any)
const DovanuKuponaiRoute = DovanuKuponaiRouteImport.update({
  id: '/dovanu-kuponai',
  path: '/dovanu-kuponai',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRouteRoute = EnRouteRouteImport.update({
  id: '/en',
  path: '/en',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeV2Route = HomeV2RouteImport.update({
  id: '/home-v2',
  path: '/home-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktaiRoute = KontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => rootRouteImport,
} as any)
const LaisviKambariaiRoute = LaisviKambariaiRouteImport.update({
  id: '/laisvi-kambariai',
  path: '/laisvi-kambariai',
  getParentRoute: () => rootRouteImport,
} as any)
const NamelisRoute = NamelisRouteImport.update({
  id: '/namelis',
  path: '/namelis',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivatumoPolitikaRoute = PrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => rootRouteImport,
} as any)
const RestobarasRoute = RestobarasRouteImport.update({
  id: '/restobaras',
  path: '/restobaras',
  getParentRoute: () => rootRouteImport,
} as any)
const SaunaRoute = SaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TaisyklesRoute = TaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentaiIndexRoute = ApartamentaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApartamentaiPropertyIdRoute = ApartamentaiPropertyIdRouteImport.update({
  id: '/$propertyId',
  path: '/$propertyId',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApartamentaiStandartiniaiRoute =
  ApartamentaiStandartiniaiRouteImport.update({
    id: '/standartiniai',
    path: '/standartiniai',
    getParentRoute: () => ApartamentaiRoute,
  } as any)
const ApartamentaiSuTerasaRoute = ApartamentaiSuTerasaRouteImport.update({
  id: '/su-terasa',
  path: '/su-terasa',
  getParentRoute: () => ApartamentaiRoute,
} as any)
const ApieIndexRoute = ApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApieRoute,
} as any)
const ApieTaisyklesRoute = ApieTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => ApieRoute,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnApartamentaiRoute = EnApartamentaiRouteImport.update({
  id: '/apartamentai',
  path: '/apartamentai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnApieRoute = EnApieRouteImport.update({
  id: '/apie',
  path: '/apie',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnBanketineSaleRoute = EnBanketineSaleRouteImport.update({
  id: '/banketine-sale',
  path: '/banketine-sale',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnDovanuKuponaiRoute = EnDovanuKuponaiRouteImport.update({
  id: '/dovanu-kuponai',
  path: '/dovanu-kuponai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnHomeV2Route = EnHomeV2RouteImport.update({
  id: '/home-v2',
  path: '/home-v2',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnKontaktaiRoute = EnKontaktaiRouteImport.update({
  id: '/kontaktai',
  path: '/kontaktai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnLaisviKambariaiRoute = EnLaisviKambariaiRouteImport.update({
  id: '/laisvi-kambariai',
  path: '/laisvi-kambariai',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnNamelisRoute = EnNamelisRouteImport.update({
  id: '/namelis',
  path: '/namelis',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnPrivatumoPolitikaRoute = EnPrivatumoPolitikaRouteImport.update({
  id: '/privatumo-politika',
  path: '/privatumo-politika',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnRestobarasRoute = EnRestobarasRouteImport.update({
  id: '/restobaras',
  path: '/restobaras',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnSaunaRoute = EnSaunaRouteImport.update({
  id: '/sauna',
  path: '/sauna',
  getParentRoute: () => EnRouteRoute,
} as any)
const EnTaisyklesRoute = EnTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => EnRouteRoute,
} as any)
const RezervacijaPatvirtintaRoute = RezervacijaPatvirtintaRouteImport.update({
  id: '/rezervacija/patvirtinta',
  path: '/rezervacija/patvirtinta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApartamentaiTipasCategorySlugRoute =
  ApartamentaiTipasCategorySlugRouteImport.update({
    id: '/tipas/$categorySlug',
    path: '/tipas/$categorySlug',
    getParentRoute: () => ApartamentaiRoute,
  } as any)
const EnApartamentaiIndexRoute = EnApartamentaiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnApartamentaiRoute,
} as any)
const EnApartamentaiPropertyIdRoute =
  EnApartamentaiPropertyIdRouteImport.update({
    id: '/$propertyId',
    path: '/$propertyId',
    getParentRoute: () => EnApartamentaiRoute,
  } as any)
const EnApartamentaiStandartiniaiRoute =
  EnApartamentaiStandartiniaiRouteImport.update({
    id: '/standartiniai',
    path: '/standartiniai',
    getParentRoute: () => EnApartamentaiRoute,
  } as any)
const EnApartamentaiSuTerasaRoute = EnApartamentaiSuTerasaRouteImport.update({
  id: '/su-terasa',
  path: '/su-terasa',
  getParentRoute: () => EnApartamentaiRoute,
} as any)
const EnApieIndexRoute = EnApieIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnApieRoute,
} as any)
const EnApieTaisyklesRoute = EnApieTaisyklesRouteImport.update({
  id: '/taisykles',
  path: '/taisykles',
  getParentRoute: () => EnApieRoute,
} as any)
const EnRezervacijaPatvirtintaRoute =
  EnRezervacijaPatvirtintaRouteImport.update({
    id: '/rezervacija/patvirtinta',
    path: '/rezervacija/patvirtinta',
    getParentRoute: () => EnRouteRoute,
  } as any)
const EnApartamentaiTipasCategorySlugRoute =
  EnApartamentaiTipasCategorySlugRouteImport.update({
    id: '/tipas/$categorySlug',
    path: '/tipas/$categorySlug',
    getParentRoute: () => EnApartamentaiRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/apartamentai': typeof ApartamentaiRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/home-v2': typeof HomeV2Route
  '/kontaktai': typeof KontaktaiRoute
  '/laisvi-kambariai': typeof LaisviKambariaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/restobaras': typeof RestobarasRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/en/apartamentai': typeof EnApartamentaiRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/banketine-sale': typeof EnBanketineSaleRoute
  '/en/dovanu-kuponai': typeof EnDovanuKuponaiRoute
  '/en/home-v2': typeof EnHomeV2Route
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/laisvi-kambariai': typeof EnLaisviKambariaiRoute
  '/en/namelis': typeof EnNamelisRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/restobaras': typeof EnRestobarasRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai/': typeof ApartamentaiIndexRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
  '/en/apartamentai/$propertyId': typeof EnApartamentaiPropertyIdRoute
  '/en/apartamentai/standartiniai': typeof EnApartamentaiStandartiniaiRoute
  '/en/apartamentai/su-terasa': typeof EnApartamentaiSuTerasaRoute
  '/en/apie/taisykles': typeof EnApieTaisyklesRoute
  '/en/rezervacija/patvirtinta': typeof EnRezervacijaPatvirtintaRoute
  '/en/apartamentai/': typeof EnApartamentaiIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
  '/en/apartamentai/tipas/$categorySlug': typeof EnApartamentaiTipasCategorySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/home-v2': typeof HomeV2Route
  '/kontaktai': typeof KontaktaiRoute
  '/laisvi-kambariai': typeof LaisviKambariaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/restobaras': typeof RestobarasRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/en/banketine-sale': typeof EnBanketineSaleRoute
  '/en/dovanu-kuponai': typeof EnDovanuKuponaiRoute
  '/en/home-v2': typeof EnHomeV2Route
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/laisvi-kambariai': typeof EnLaisviKambariaiRoute
  '/en/namelis': typeof EnNamelisRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/restobaras': typeof EnRestobarasRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai': typeof ApartamentaiIndexRoute
  '/apie': typeof ApieIndexRoute
  '/en': typeof EnIndexRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
  '/en/apartamentai/$propertyId': typeof EnApartamentaiPropertyIdRoute
  '/en/apartamentai/standartiniai': typeof EnApartamentaiStandartiniaiRoute
  '/en/apartamentai/su-terasa': typeof EnApartamentaiSuTerasaRoute
  '/en/apie/taisykles': typeof EnApieTaisyklesRoute
  '/en/rezervacija/patvirtinta': typeof EnRezervacijaPatvirtintaRoute
  '/en/apartamentai': typeof EnApartamentaiIndexRoute
  '/en/apie': typeof EnApieIndexRoute
  '/en/apartamentai/tipas/$categorySlug': typeof EnApartamentaiTipasCategorySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en': typeof EnRouteRouteWithChildren
  '/apartamentai': typeof ApartamentaiRouteWithChildren
  '/apie': typeof ApieRouteWithChildren
  '/banketine-sale': typeof BanketineSaleRoute
  '/dovanu-kuponai': typeof DovanuKuponaiRoute
  '/home-v2': typeof HomeV2Route
  '/kontaktai': typeof KontaktaiRoute
  '/laisvi-kambariai': typeof LaisviKambariaiRoute
  '/namelis': typeof NamelisRoute
  '/privatumo-politika': typeof PrivatumoPolitikaRoute
  '/restobaras': typeof RestobarasRoute
  '/sauna': typeof SaunaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/taisykles': typeof TaisyklesRoute
  '/apartamentai/$propertyId': typeof ApartamentaiPropertyIdRoute
  '/apartamentai/standartiniai': typeof ApartamentaiStandartiniaiRoute
  '/apartamentai/su-terasa': typeof ApartamentaiSuTerasaRoute
  '/apie/taisykles': typeof ApieTaisyklesRoute
  '/en/apartamentai': typeof EnApartamentaiRouteWithChildren
  '/en/apie': typeof EnApieRouteWithChildren
  '/en/banketine-sale': typeof EnBanketineSaleRoute
  '/en/dovanu-kuponai': typeof EnDovanuKuponaiRoute
  '/en/home-v2': typeof EnHomeV2Route
  '/en/kontaktai': typeof EnKontaktaiRoute
  '/en/laisvi-kambariai': typeof EnLaisviKambariaiRoute
  '/en/namelis': typeof EnNamelisRoute
  '/en/privatumo-politika': typeof EnPrivatumoPolitikaRoute
  '/en/restobaras': typeof EnRestobarasRoute
  '/en/sauna': typeof EnSaunaRoute
  '/en/taisykles': typeof EnTaisyklesRoute
  '/rezervacija/patvirtinta': typeof RezervacijaPatvirtintaRoute
  '/apartamentai/': typeof ApartamentaiIndexRoute
  '/apie/': typeof ApieIndexRoute
  '/en/': typeof EnIndexRoute
  '/apartamentai/tipas/$categorySlug': typeof ApartamentaiTipasCategorySlugRoute
  '/en/apartamentai/$propertyId': typeof EnApartamentaiPropertyIdRoute
  '/en/apartamentai/standartiniai': typeof EnApartamentaiStandartiniaiRoute
  '/en/apartamentai/su-terasa': typeof EnApartamentaiSuTerasaRoute
  '/en/apie/taisykles': typeof EnApieTaisyklesRoute
  '/en/rezervacija/patvirtinta': typeof EnRezervacijaPatvirtintaRoute
  '/en/apartamentai/': typeof EnApartamentaiIndexRoute
  '/en/apie/': typeof EnApieIndexRoute
  '/en/apartamentai/tipas/$categorySlug': typeof EnApartamentaiTipasCategorySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en'
    | '/apartamentai'
    | '/apie'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/home-v2'
    | '/kontaktai'
    | '/laisvi-kambariai'
    | '/namelis'
    | '/privatumo-politika'
    | '/restobaras'
    | '/sauna'
    | '/sitemap.xml'
    | '/taisykles'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/en/apartamentai'
    | '/en/apie'
    | '/en/banketine-sale'
    | '/en/dovanu-kuponai'
    | '/en/home-v2'
    | '/en/kontaktai'
    | '/en/laisvi-kambariai'
    | '/en/namelis'
    | '/en/privatumo-politika'
    | '/en/restobaras'
    | '/en/sauna'
    | '/en/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai/'
    | '/apie/'
    | '/en/'
    | '/apartamentai/tipas/$categorySlug'
    | '/en/apartamentai/$propertyId'
    | '/en/apartamentai/standartiniai'
    | '/en/apartamentai/su-terasa'
    | '/en/apie/taisykles'
    | '/en/rezervacija/patvirtinta'
    | '/en/apartamentai/'
    | '/en/apie/'
    | '/en/apartamentai/tipas/$categorySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/home-v2'
    | '/kontaktai'
    | '/laisvi-kambariai'
    | '/namelis'
    | '/privatumo-politika'
    | '/restobaras'
    | '/sauna'
    | '/sitemap.xml'
    | '/taisykles'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/en/banketine-sale'
    | '/en/dovanu-kuponai'
    | '/en/home-v2'
    | '/en/kontaktai'
    | '/en/laisvi-kambariai'
    | '/en/namelis'
    | '/en/privatumo-politika'
    | '/en/restobaras'
    | '/en/sauna'
    | '/en/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai'
    | '/apie'
    | '/en'
    | '/apartamentai/tipas/$categorySlug'
    | '/en/apartamentai/$propertyId'
    | '/en/apartamentai/standartiniai'
    | '/en/apartamentai/su-terasa'
    | '/en/apie/taisykles'
    | '/en/rezervacija/patvirtinta'
    | '/en/apartamentai'
    | '/en/apie'
    | '/en/apartamentai/tipas/$categorySlug'
  id:
    | '__root__'
    | '/'
    | '/en'
    | '/apartamentai'
    | '/apie'
    | '/banketine-sale'
    | '/dovanu-kuponai'
    | '/home-v2'
    | '/kontaktai'
    | '/laisvi-kambariai'
    | '/namelis'
    | '/privatumo-politika'
    | '/restobaras'
    | '/sauna'
    | '/sitemap.xml'
    | '/taisykles'
    | '/apartamentai/$propertyId'
    | '/apartamentai/standartiniai'
    | '/apartamentai/su-terasa'
    | '/apie/taisykles'
    | '/en/apartamentai'
    | '/en/apie'
    | '/en/banketine-sale'
    | '/en/dovanu-kuponai'
    | '/en/home-v2'
    | '/en/kontaktai'
    | '/en/laisvi-kambariai'
    | '/en/namelis'
    | '/en/privatumo-politika'
    | '/en/restobaras'
    | '/en/sauna'
    | '/en/taisykles'
    | '/rezervacija/patvirtinta'
    | '/apartamentai/'
    | '/apie/'
    | '/en/'
    | '/apartamentai/tipas/$categorySlug'
    | '/en/apartamentai/$propertyId'
    | '/en/apartamentai/standartiniai'
    | '/en/apartamentai/su-terasa'
    | '/en/apie/taisykles'
    | '/en/rezervacija/patvirtinta'
    | '/en/apartamentai/'
    | '/en/apie/'
    | '/en/apartamentai/tipas/$categorySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnRouteRoute: typeof EnRouteRouteWithChildren
  ApartamentaiRoute: typeof ApartamentaiRouteWithChildren
  ApieRoute: typeof ApieRouteWithChildren
  BanketineSaleRoute: typeof BanketineSaleRoute
  DovanuKuponaiRoute: typeof DovanuKuponaiRoute
  HomeV2Route: typeof HomeV2Route
  KontaktaiRoute: typeof KontaktaiRoute
  LaisviKambariaiRoute: typeof LaisviKambariaiRoute
  NamelisRoute: typeof NamelisRoute
  PrivatumoPolitikaRoute: typeof PrivatumoPolitikaRoute
  RestobarasRoute: typeof RestobarasRoute
  SaunaRoute: typeof SaunaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TaisyklesRoute: typeof TaisyklesRoute
  RezervacijaPatvirtintaRoute: typeof RezervacijaPatvirtintaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentai': {
      id: '/apartamentai'
      path: '/apartamentai'
      fullPath: '/apartamentai'
      preLoaderRoute: typeof ApartamentaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apie': {
      id: '/apie'
      path: '/apie'
      fullPath: '/apie'
      preLoaderRoute: typeof ApieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banketine-sale': {
      id: '/banketine-sale'
      path: '/banketine-sale'
      fullPath: '/banketine-sale'
      preLoaderRoute: typeof BanketineSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dovanu-kuponai': {
      id: '/dovanu-kuponai'
      path: '/dovanu-kuponai'
      fullPath: '/dovanu-kuponai'
      preLoaderRoute: typeof DovanuKuponaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en': {
      id: '/en'
      path: '/en'
      fullPath: '/en'
      preLoaderRoute: typeof EnRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-v2': {
      id: '/home-v2'
      path: '/home-v2'
      fullPath: '/home-v2'
      preLoaderRoute: typeof HomeV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontaktai': {
      id: '/kontaktai'
      path: '/kontaktai'
      fullPath: '/kontaktai'
      preLoaderRoute: typeof KontaktaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laisvi-kambariai': {
      id: '/laisvi-kambariai'
      path: '/laisvi-kambariai'
      fullPath: '/laisvi-kambariai'
      preLoaderRoute: typeof LaisviKambariaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namelis': {
      id: '/namelis'
      path: '/namelis'
      fullPath: '/namelis'
      preLoaderRoute: typeof NamelisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privatumo-politika': {
      id: '/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/privatumo-politika'
      preLoaderRoute: typeof PrivatumoPolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restobaras': {
      id: '/restobaras'
      path: '/restobaras'
      fullPath: '/restobaras'
      preLoaderRoute: typeof RestobarasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sauna': {
      id: '/sauna'
      path: '/sauna'
      fullPath: '/sauna'
      preLoaderRoute: typeof SaunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/taisykles': {
      id: '/taisykles'
      path: '/taisykles'
      fullPath: '/taisykles'
      preLoaderRoute: typeof TaisyklesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentai/': {
      id: '/apartamentai/'
      path: '/'
      fullPath: '/apartamentai/'
      preLoaderRoute: typeof ApartamentaiIndexRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/$propertyId': {
      id: '/apartamentai/$propertyId'
      path: '/$propertyId'
      fullPath: '/apartamentai/$propertyId'
      preLoaderRoute: typeof ApartamentaiPropertyIdRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/standartiniai': {
      id: '/apartamentai/standartiniai'
      path: '/standartiniai'
      fullPath: '/apartamentai/standartiniai'
      preLoaderRoute: typeof ApartamentaiStandartiniaiRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apartamentai/su-terasa': {
      id: '/apartamentai/su-terasa'
      path: '/su-terasa'
      fullPath: '/apartamentai/su-terasa'
      preLoaderRoute: typeof ApartamentaiSuTerasaRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/apie/': {
      id: '/apie/'
      path: '/'
      fullPath: '/apie/'
      preLoaderRoute: typeof ApieIndexRouteImport
      parentRoute: typeof ApieRoute
    }
    '/apie/taisykles': {
      id: '/apie/taisykles'
      path: '/taisykles'
      fullPath: '/apie/taisykles'
      preLoaderRoute: typeof ApieTaisyklesRouteImport
      parentRoute: typeof ApieRoute
    }
    '/en/': {
      id: '/en/'
      path: '/'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/apartamentai': {
      id: '/en/apartamentai'
      path: '/apartamentai'
      fullPath: '/en/apartamentai'
      preLoaderRoute: typeof EnApartamentaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/apie': {
      id: '/en/apie'
      path: '/apie'
      fullPath: '/en/apie'
      preLoaderRoute: typeof EnApieRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/banketine-sale': {
      id: '/en/banketine-sale'
      path: '/banketine-sale'
      fullPath: '/en/banketine-sale'
      preLoaderRoute: typeof EnBanketineSaleRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/dovanu-kuponai': {
      id: '/en/dovanu-kuponai'
      path: '/dovanu-kuponai'
      fullPath: '/en/dovanu-kuponai'
      preLoaderRoute: typeof EnDovanuKuponaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/home-v2': {
      id: '/en/home-v2'
      path: '/home-v2'
      fullPath: '/en/home-v2'
      preLoaderRoute: typeof EnHomeV2RouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/kontaktai': {
      id: '/en/kontaktai'
      path: '/kontaktai'
      fullPath: '/en/kontaktai'
      preLoaderRoute: typeof EnKontaktaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/laisvi-kambariai': {
      id: '/en/laisvi-kambariai'
      path: '/laisvi-kambariai'
      fullPath: '/en/laisvi-kambariai'
      preLoaderRoute: typeof EnLaisviKambariaiRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/namelis': {
      id: '/en/namelis'
      path: '/namelis'
      fullPath: '/en/namelis'
      preLoaderRoute: typeof EnNamelisRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/privatumo-politika': {
      id: '/en/privatumo-politika'
      path: '/privatumo-politika'
      fullPath: '/en/privatumo-politika'
      preLoaderRoute: typeof EnPrivatumoPolitikaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/restobaras': {
      id: '/en/restobaras'
      path: '/restobaras'
      fullPath: '/en/restobaras'
      preLoaderRoute: typeof EnRestobarasRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/sauna': {
      id: '/en/sauna'
      path: '/sauna'
      fullPath: '/en/sauna'
      preLoaderRoute: typeof EnSaunaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/taisykles': {
      id: '/en/taisykles'
      path: '/taisykles'
      fullPath: '/en/taisykles'
      preLoaderRoute: typeof EnTaisyklesRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/rezervacija/patvirtinta': {
      id: '/rezervacija/patvirtinta'
      path: '/rezervacija/patvirtinta'
      fullPath: '/rezervacija/patvirtinta'
      preLoaderRoute: typeof RezervacijaPatvirtintaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apartamentai/tipas/$categorySlug': {
      id: '/apartamentai/tipas/$categorySlug'
      path: '/tipas/$categorySlug'
      fullPath: '/apartamentai/tipas/$categorySlug'
      preLoaderRoute: typeof ApartamentaiTipasCategorySlugRouteImport
      parentRoute: typeof ApartamentaiRoute
    }
    '/en/apartamentai/': {
      id: '/en/apartamentai/'
      path: '/'
      fullPath: '/en/apartamentai/'
      preLoaderRoute: typeof EnApartamentaiIndexRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apartamentai/$propertyId': {
      id: '/en/apartamentai/$propertyId'
      path: '/$propertyId'
      fullPath: '/en/apartamentai/$propertyId'
      preLoaderRoute: typeof EnApartamentaiPropertyIdRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apartamentai/standartiniai': {
      id: '/en/apartamentai/standartiniai'
      path: '/standartiniai'
      fullPath: '/en/apartamentai/standartiniai'
      preLoaderRoute: typeof EnApartamentaiStandartiniaiRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apartamentai/su-terasa': {
      id: '/en/apartamentai/su-terasa'
      path: '/su-terasa'
      fullPath: '/en/apartamentai/su-terasa'
      preLoaderRoute: typeof EnApartamentaiSuTerasaRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
    '/en/apie/': {
      id: '/en/apie/'
      path: '/'
      fullPath: '/en/apie/'
      preLoaderRoute: typeof EnApieIndexRouteImport
      parentRoute: typeof EnApieRoute
    }
    '/en/apie/taisykles': {
      id: '/en/apie/taisykles'
      path: '/taisykles'
      fullPath: '/en/apie/taisykles'
      preLoaderRoute: typeof EnApieTaisyklesRouteImport
      parentRoute: typeof EnApieRoute
    }
    '/en/rezervacija/patvirtinta': {
      id: '/en/rezervacija/patvirtinta'
      path: '/rezervacija/patvirtinta'
      fullPath: '/en/rezervacija/patvirtinta'
      preLoaderRoute: typeof EnRezervacijaPatvirtintaRouteImport
      parentRoute: typeof EnRouteRoute
    }
    '/en/apartamentai/tipas/$categorySlug': {
      id: '/en/apartamentai/tipas/$categorySlug'
      path: '/tipas/$categorySlug'
      fullPath: '/en/apartamentai/tipas/$categorySlug'
      preLoaderRoute: typeof EnApartamentaiTipasCategorySlugRouteImport
      parentRoute: typeof EnApartamentaiRoute
    }
  }
}

interface EnApartamentaiRouteChildren {
  EnApartamentaiPropertyIdRoute: typeof EnApartamentaiPropertyIdRoute
  EnApartamentaiStandartiniaiRoute: typeof EnApartamentaiStandartiniaiRoute
  EnApartamentaiSuTerasaRoute: typeof EnApartamentaiSuTerasaRoute
  EnApartamentaiIndexRoute: typeof EnApartamentaiIndexRoute
  EnApartamentaiTipasCategorySlugRoute: typeof EnApartamentaiTipasCategorySlugRoute
}

const EnApartamentaiRouteChildren: EnApartamentaiRouteChildren = {
  EnApartamentaiPropertyIdRoute: EnApartamentaiPropertyIdRoute,
  EnApartamentaiStandartiniaiRoute: EnApartamentaiStandartiniaiRoute,
  EnApartamentaiSuTerasaRoute: EnApartamentaiSuTerasaRoute,
  EnApartamentaiIndexRoute: EnApartamentaiIndexRoute,
  EnApartamentaiTipasCategorySlugRoute: EnApartamentaiTipasCategorySlugRoute,
}

const EnApartamentaiRouteWithChildren = EnApartamentaiRoute._addFileChildren(
  EnApartamentaiRouteChildren,
)

interface EnApieRouteChildren {
  EnApieTaisyklesRoute: typeof EnApieTaisyklesRoute
  EnApieIndexRoute: typeof EnApieIndexRoute
}

const EnApieRouteChildren: EnApieRouteChildren = {
  EnApieTaisyklesRoute: EnApieTaisyklesRoute,
  EnApieIndexRoute: EnApieIndexRoute,
}

const EnApieRouteWithChildren =
  EnApieRoute._addFileChildren(EnApieRouteChildren)

interface EnRouteRouteChildren {
  EnApartamentaiRoute: typeof EnApartamentaiRouteWithChildren
  EnApieRoute: typeof EnApieRouteWithChildren
  EnBanketineSaleRoute: typeof EnBanketineSaleRoute
  EnDovanuKuponaiRoute: typeof EnDovanuKuponaiRoute
  EnHomeV2Route: typeof EnHomeV2Route
  EnKontaktaiRoute: typeof EnKontaktaiRoute
  EnLaisviKambariaiRoute: typeof EnLaisviKambariaiRoute
  EnNamelisRoute: typeof EnNamelisRoute
  EnPrivatumoPolitikaRoute: typeof EnPrivatumoPolitikaRoute
  EnRestobarasRoute: typeof EnRestobarasRoute
  EnSaunaRoute: typeof EnSaunaRoute
  EnTaisyklesRoute: typeof EnTaisyklesRoute
  EnIndexRoute: typeof EnIndexRoute
  EnRezervacijaPatvirtintaRoute: typeof EnRezervacijaPatvirtintaRoute
}

const EnRouteRouteChildren: EnRouteRouteChildren = {
  EnApartamentaiRoute: EnApartamentaiRouteWithChildren,
  EnApieRoute: EnApieRouteWithChildren,
  EnBanketineSaleRoute: EnBanketineSaleRoute,
  EnDovanuKuponaiRoute: EnDovanuKuponaiRoute,
  EnHomeV2Route: EnHomeV2Route,
  EnKontaktaiRoute: EnKontaktaiRoute,
  EnLaisviKambariaiRoute: EnLaisviKambariaiRoute,
  EnNamelisRoute: EnNamelisRoute,
  EnPrivatumoPolitikaRoute: EnPrivatumoPolitikaRoute,
  EnRestobarasRoute: EnRestobarasRoute,
  EnSaunaRoute: EnSaunaRoute,
  EnTaisyklesRoute: EnTaisyklesRoute,
  EnIndexRoute: EnIndexRoute,
  EnRezervacijaPatvirtintaRoute: EnRezervacijaPatvirtintaRoute,
}

const EnRouteRouteWithChildren =
  EnRouteRoute._addFileChildren(EnRouteRouteChildren)

interface ApartamentaiRouteChildren {
  ApartamentaiPropertyIdRoute: typeof ApartamentaiPropertyIdRoute
  ApartamentaiStandartiniaiRoute: typeof ApartamentaiStandartiniaiRoute
  ApartamentaiSuTerasaRoute: typeof ApartamentaiSuTerasaRoute
  ApartamentaiIndexRoute: typeof ApartamentaiIndexRoute
  ApartamentaiTipasCategorySlugRoute: typeof ApartamentaiTipasCategorySlugRoute
}

const ApartamentaiRouteChildren: ApartamentaiRouteChildren = {
  ApartamentaiPropertyIdRoute: ApartamentaiPropertyIdRoute,
  ApartamentaiStandartiniaiRoute: ApartamentaiStandartiniaiRoute,
  ApartamentaiSuTerasaRoute: ApartamentaiSuTerasaRoute,
  ApartamentaiIndexRoute: ApartamentaiIndexRoute,
  ApartamentaiTipasCategorySlugRoute: ApartamentaiTipasCategorySlugRoute,
}

const ApartamentaiRouteWithChildren = ApartamentaiRoute._addFileChildren(
  ApartamentaiRouteChildren,
)

interface ApieRouteChildren {
  ApieTaisyklesRoute: typeof ApieTaisyklesRoute
  ApieIndexRoute: typeof ApieIndexRoute
}

const ApieRouteChildren: ApieRouteChildren = {
  ApieTaisyklesRoute: ApieTaisyklesRoute,
  ApieIndexRoute: ApieIndexRoute,
}

const ApieRouteWithChildren = ApieRoute._addFileChildren(ApieRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnRouteRoute: EnRouteRouteWithChildren,
  ApartamentaiRoute: ApartamentaiRouteWithChildren,
  ApieRoute: ApieRouteWithChildren,
  BanketineSaleRoute: BanketineSaleRoute,
  DovanuKuponaiRoute: DovanuKuponaiRoute,
  HomeV2Route: HomeV2Route,
  KontaktaiRoute: KontaktaiRoute,
  LaisviKambariaiRoute: LaisviKambariaiRoute,
  NamelisRoute: NamelisRoute,
  PrivatumoPolitikaRoute: PrivatumoPolitikaRoute,
  RestobarasRoute: RestobarasRoute,
  SaunaRoute: SaunaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TaisyklesRoute: TaisyklesRoute,
  RezervacijaPatvirtintaRoute: RezervacijaPatvirtintaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
